### ISSUE TITLE
A really tiny bug

### ISSUE THREAD

**Issue by Comrade-Riley** [tankerguy1917/Project-Agame#1]
There's this tiny bug, I got to run it but then I realise that there is nothing to run. I know it's really minor but I really wish you'd fix this bug.

**Comment by tankerguy1917** [comment]
ok. yeah, i havent really had any ideas on what to add to this yet, so its empty for now

**Comment by Comrade-Riley** [comment]
> ok. yeah, i havent really had any ideas on what to add to this yet, so its empty for now

Who are you btw? I saw that you followed me on github so I assume you're from discord or something.

**Comment by tankerguy1917** [comment]
im someone from repl. i responded to a post you made on an older account and you told me that you used a different account

**Comment by Comrade-Riley** [comment]
> im someone from repl. i responded to a post you made on an older account and you told me that you used a different account

Oh, I thought you were someone from discord bc I got my github attached to it

**Comment by tankerguy1917** [comment]
no. you have a link to your github on your repl profile

**Comment by Comrade-Riley** [comment]
> no. you have a link to your github on your repl profile

Oh, Idr use repl anymore, only for hosting things like a discord bot and stuff like that.

**Comment by Comrade-Riley** [comment]
> no. you have a link to your github on your repl profile

also you should

**Comment by Comrade-Riley** [comment]
closing it bc there's no point in having it open
